---
version: '3.9'

services:
  shepherd:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - database
  database:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - ./db-data/:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    env_file:
      - .env
      # environment:
      #   - PGADMIN_DEFAULT_EMAIL=alwindoss84@gmail.com
      #   - PGADMIN_DEFAULT_PASSWORD=password
      # - PGADMIN_DEFAULT_PASSWORD_FILE=pwdfile.txt
    ports:
      - 8081:80
